todo/urls.py
from django.urls import path

from todo.views import (
    IndexListView,
    IndexCreateView,
    IndexUpdateView,
    IndexDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, change_readiness,
)

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path("create/", IndexCreateView.as_view(), name="index-create"),
    path("<int:pk>/update/", IndexUpdateView.as_view(), name="index-update"),
    path("<int:pk>/delete/", IndexDeleteView.as_view(), name="index-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("<int:pk>/change-readiness/", change_readiness, name="change-readiness")
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo"))
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    readiness = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ["readiness"]

    def __str__(self):
        return f"{self.content} {self.readiness}"

todo/forms.py
from django import forms

from todo.models import Tag, Task


class IndexForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta:
        model = Task
        fields = "__all__"

todo/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import IndexForm
from todo.models import Tag, Task


class IndexListView(generic.ListView):
    model = Task
    template_name = "todo/index.html"
    paginate_by = 3


class IndexCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:index")
    form_class = IndexForm


class IndexUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("todo:index")
    form_class = IndexForm


class IndexDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


def change_readiness(request, pk):
    task = Task.objects.get(id=pk)
    task.readiness = not task.readiness
    task.save()
    return redirect("todo:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
  <link rel="icon" type="image/x-icon" href="{% static "icon.png" %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% block content %}{% endblock %}
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}

      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>

    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}

      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>

    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:index-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>

  <br>
  {% if task_list %}

    {% for task in task_list %}
      <h4>
        *{{ task.content }}
        {% if task.readiness %}
          <p style="color: green">Done</p>
        {% else %}
          <p style="color: red">Not done</p>
        {% endif %}
      </h4>


      {% if task.readiness %}
        <a href="{% url 'todo:change-readiness' pk=task.id %}" class="btn btn-secondary link-to-page">
          Undo
        </a>
      {% else %}
        <a href="{% url 'todo:change-readiness' pk=task.id %}" class="btn btn-success link-to-page">
          Complete
        </a>
      {% endif %}



      <p>Created: {{ task.created_at }}</p>
      {% if task.deadline %}
        <p style="color: red">Deadline: {{ task.deadline }}</p>
      {% endif %}

      <h6>
        Tags:
        {% for tag in task.tags.all %}
          {{ tag }}
        {% endfor %}
        <a class="text" href="{% url 'todo:index-update' pk=task.id %}">Update</a>
        <a class="text" href="{% url 'todo:index-delete' pk=task.id %}">Delete</a>
      </h6>
      <br>
    {% endfor %}
  {% else %}
    <h3>You don't have any task</h3>
    <p>
      Click here to create:
      <a href="{% url 'todo:index-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag</h1>
  <h3>Are you sure you want to delete tag "{{ tag.name }}"?</h3>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    Tags
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a class="btn btn-dark" href="{% url 'todo:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a class="btn btn-dark" href="{% url 'todo:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <h3>Sorry, you don't have any tag</h3>
  {% endif %}

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>
  <h3>Are you sure you want to delete task "{{ task.content }}"?</h3>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}